language: node_js
node_js:
  - "stable"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
script: "npm run test-coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
